using StrategyUnits;

Barrack barrack = new Barrack();
Cottage cottage = new Cottage();
MagicFountain magicFountain1 = new MagicFountain();
Footman footman = barrack.CreateFootman();
Footman footman2 = barrack.CreateFootmanOfficer();
Peasant ps1 = cottage.CreatePeasant();
Bishop bishop1 = magicFountain1.CreateBishop();
Berserker berserker = barrack.CreateBerserker();
Paladin paladin = magicFountain1.CreatePalladin();

ps1.ShowInfo();
berserker.ShowInfo();
berserker.Attack(ps1);
ps1.ShowInfo();
footman2.Attack(berserker);
footman2.Attack(berserker);
footman2.Attack(berserker);
footman2.Attack(berserker);
footman2.Attack(berserker);
berserker.Frenzy();
berserker.Attack(ps1);
bishop1.Heal(berserker);
berserker.ShowInfo();
ps1.ShowInfo();
paladin.ShowInfo();
footman2.Attack(paladin);
paladin.Prayer();
paladin.ShowInfo();
Zelot zelot = magicFountain1.CreateZelot();
zelot.ShowInfo();
berserker.Attack(zelot);
berserker.Attack(zelot);
berserker.Attack(zelot);
footman.Attack(zelot);
zelot.Prayer();
zelot.ShowInfo();